### PR TITLE
fix anon not affecting goal and not expiring

### LINKED ISSUE #259: Update goal on anonymous contributions

### LINKED ISSUE #261: Fix Cheese goal not resetting each day.
Apparently set operations clear expiration.

### PR DESCRIPTION
**Pull request by albertcui**
Fixes #261 
Fixes #259

### CODE REVIEW

File: web.js [hunk 1]
```diff
@@ -259,30 +259,30 @@ app.route('/confirm').get(function(req, res, next) {
...
-                            redis.setex("cheese_goal", 86400 - moment().unix() % 86400, cheeseAmount);
+            redis.incrby("cheese_goal", cheeseAmount, function(err, val) {
+                if (!err && val == cheeseAmount) {
+                    // cheeseAmount is string, val is number, just let JS cast
+                    // this condition indicates the key is new
+                    redis.expire("cheese_goal", 86400 - moment().unix() % 86400);
+                }
+                
+                if (req.user && payment.transactions[0]) {
+                    var cheeseTotal = (req.user.cheese || 0) + parseInt(payment.transactions[0].amount.total)
```
Comment (howardc93) [inline web.js]: option: use mongodb inc:
http://docs.mongodb.org/manual/reference/operator/update/inc/

Comment (albertcui) [inline web.js]: TBH i don't see much reason to use inc since we're not doing a query to get the old count anyway (taken care of by deserialization).

Comment (howardc93) [inline web.js]: It might look a bit cleaner, but I'm okay either way.
